# Generated by Django 5.1.3 on 2024-11-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'can add book'), ('can_change_book', 'can change book'), ('can_delete_book', 'can delete book')]},
        ),
    ]
